# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import market_pest_pb2 as market__pest__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in market_pest_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MarketAgentServiceStub(object):
    """── Market Price agent ──────────────────────────────────────────
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetMarketAdvisory = channel.unary_unary(
                '/paddy.MarketAgentService/GetMarketAdvisory',
                request_serializer=market__pest__pb2.MarketRequest.SerializeToString,
                response_deserializer=market__pest__pb2.MarketResponse.FromString,
                _registered_method=True)


class MarketAgentServiceServicer(object):
    """── Market Price agent ──────────────────────────────────────────
    """

    def GetMarketAdvisory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MarketAgentServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetMarketAdvisory': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMarketAdvisory,
                    request_deserializer=market__pest__pb2.MarketRequest.FromString,
                    response_serializer=market__pest__pb2.MarketResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'paddy.MarketAgentService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('paddy.MarketAgentService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MarketAgentService(object):
    """── Market Price agent ──────────────────────────────────────────
    """

    @staticmethod
    def GetMarketAdvisory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/paddy.MarketAgentService/GetMarketAdvisory',
            market__pest__pb2.MarketRequest.SerializeToString,
            market__pest__pb2.MarketResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class PestAgentServiceStub(object):
    """── Pest Risk agent ─────────────────────────────────────────────
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetPestRisk = channel.unary_unary(
                '/paddy.PestAgentService/GetPestRisk',
                request_serializer=market__pest__pb2.PestRequest.SerializeToString,
                response_deserializer=market__pest__pb2.PestResponse.FromString,
                _registered_method=True)


class PestAgentServiceServicer(object):
    """── Pest Risk agent ─────────────────────────────────────────────
    """

    def GetPestRisk(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PestAgentServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetPestRisk': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPestRisk,
                    request_deserializer=market__pest__pb2.PestRequest.FromString,
                    response_serializer=market__pest__pb2.PestResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'paddy.PestAgentService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('paddy.PestAgentService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PestAgentService(object):
    """── Pest Risk agent ─────────────────────────────────────────────
    """

    @staticmethod
    def GetPestRisk(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/paddy.PestAgentService/GetPestRisk',
            market__pest__pb2.PestRequest.SerializeToString,
            market__pest__pb2.PestResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
