# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import paddy_agents_pb2 as paddy__agents__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in paddy_agents_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SoilAgentStub(object):
    """── Soil Agent ──────────────────────────────────────────
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetNPKProfile = channel.unary_unary(
                '/paddy.SoilAgent/GetNPKProfile',
                request_serializer=paddy__agents__pb2.DistrictRequest.SerializeToString,
                response_deserializer=paddy__agents__pb2.NPKResponse.FromString,
                _registered_method=True)
        self.GetFertilizerRec = channel.unary_unary(
                '/paddy.SoilAgent/GetFertilizerRec',
                request_serializer=paddy__agents__pb2.FertilizerRequest.SerializeToString,
                response_deserializer=paddy__agents__pb2.FertilizerResponse.FromString,
                _registered_method=True)
        self.GetSoilTrend = channel.unary_unary(
                '/paddy.SoilAgent/GetSoilTrend',
                request_serializer=paddy__agents__pb2.DistrictRequest.SerializeToString,
                response_deserializer=paddy__agents__pb2.SoilTrendResponse.FromString,
                _registered_method=True)


class SoilAgentServicer(object):
    """── Soil Agent ──────────────────────────────────────────
    """

    def GetNPKProfile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFertilizerRec(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSoilTrend(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SoilAgentServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetNPKProfile': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNPKProfile,
                    request_deserializer=paddy__agents__pb2.DistrictRequest.FromString,
                    response_serializer=paddy__agents__pb2.NPKResponse.SerializeToString,
            ),
            'GetFertilizerRec': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFertilizerRec,
                    request_deserializer=paddy__agents__pb2.FertilizerRequest.FromString,
                    response_serializer=paddy__agents__pb2.FertilizerResponse.SerializeToString,
            ),
            'GetSoilTrend': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSoilTrend,
                    request_deserializer=paddy__agents__pb2.DistrictRequest.FromString,
                    response_serializer=paddy__agents__pb2.SoilTrendResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'paddy.SoilAgent', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('paddy.SoilAgent', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SoilAgent(object):
    """── Soil Agent ──────────────────────────────────────────
    """

    @staticmethod
    def GetNPKProfile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/paddy.SoilAgent/GetNPKProfile',
            paddy__agents__pb2.DistrictRequest.SerializeToString,
            paddy__agents__pb2.NPKResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetFertilizerRec(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/paddy.SoilAgent/GetFertilizerRec',
            paddy__agents__pb2.FertilizerRequest.SerializeToString,
            paddy__agents__pb2.FertilizerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSoilTrend(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/paddy.SoilAgent/GetSoilTrend',
            paddy__agents__pb2.DistrictRequest.SerializeToString,
            paddy__agents__pb2.SoilTrendResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
