# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: paddy_agents.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'paddy_agents.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12paddy_agents.proto\x12\x05paddy\"#\n\x0f\x44istrictRequest\x12\x10\n\x08\x64istrict\x18\x01 \x01(\t\"\x92\x01\n\x11\x46\x65rtilizerRequest\x12\x10\n\x08\x64istrict\x18\x01 \x01(\t\x12\x10\n\x08nitrogen\x18\x02 \x01(\x02\x12\x12\n\nphosphorus\x18\x03 \x01(\x02\x12\x11\n\tpotassium\x18\x04 \x01(\x02\x12\n\n\x02ph\x18\x05 \x01(\x02\x12\x16\n\x0eorganic_carbon\x18\x06 \x01(\x02\x12\x0e\n\x06season\x18\x07 \x01(\t\"X\n\x0bNPKResponse\x12\x10\n\x08\x64istrict\x18\x01 \x01(\t\x12\x10\n\x08nitrogen\x18\x02 \x01(\x02\x12\x12\n\nphosphorus\x18\x03 \x01(\x02\x12\x11\n\tpotassium\x18\x04 \x01(\x02\"\x8a\x01\n\x12\x46\x65rtilizerResponse\x12\x18\n\x10urea_kg_per_acre\x18\x01 \x01(\x02\x12\x17\n\x0f\x64\x61p_kg_per_acre\x18\x02 \x01(\x02\x12\x1a\n\x12potash_kg_per_acre\x18\x03 \x01(\x02\x12\x15\n\rtiming_advice\x18\x04 \x01(\t\x12\x0e\n\x06season\x18\x05 \x01(\t\"\x8f\x01\n\x11SoilTrendResponse\x12\x10\n\x08\x64istrict\x18\x01 \x01(\t\x12\x10\n\x08ph_slope\x18\x02 \x01(\x02\x12\x15\n\rph_last_value\x18\x03 \x01(\x02\x12\x10\n\x08oc_slope\x18\x04 \x01(\x02\x12\x15\n\roc_last_value\x18\x05 \x01(\x02\x12\x16\n\x0einterpretation\x18\x06 \x01(\t2\xd3\x01\n\tSoilAgent\x12;\n\rGetNPKProfile\x12\x16.paddy.DistrictRequest\x1a\x12.paddy.NPKResponse\x12G\n\x10GetFertilizerRec\x12\x18.paddy.FertilizerRequest\x1a\x19.paddy.FertilizerResponse\x12@\n\x0cGetSoilTrend\x12\x16.paddy.DistrictRequest\x1a\x18.paddy.SoilTrendResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'paddy_agents_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DISTRICTREQUEST']._serialized_start=29
  _globals['_DISTRICTREQUEST']._serialized_end=64
  _globals['_FERTILIZERREQUEST']._serialized_start=67
  _globals['_FERTILIZERREQUEST']._serialized_end=213
  _globals['_NPKRESPONSE']._serialized_start=215
  _globals['_NPKRESPONSE']._serialized_end=303
  _globals['_FERTILIZERRESPONSE']._serialized_start=306
  _globals['_FERTILIZERRESPONSE']._serialized_end=444
  _globals['_SOILTRENDRESPONSE']._serialized_start=447
  _globals['_SOILTRENDRESPONSE']._serialized_end=590
  _globals['_SOILAGENT']._serialized_start=593
  _globals['_SOILAGENT']._serialized_end=804
# @@protoc_insertion_point(module_scope)
