// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: proto/paddy_agents.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AgentRegistration struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	AgentName     string                 `protobuf:"bytes,2,opt,name=agent_name,json=agentName,proto3" json:"agent_name,omitempty"`
	AgentType     string                 `protobuf:"bytes,3,opt,name=agent_type,json=agentType,proto3" json:"agent_type,omitempty"` // "WEATHER" | "SOIL" | "CROP_HEALTH" | "MARKET" | "PEST_RISK"
	Host          string                 `protobuf:"bytes,4,opt,name=host,proto3" json:"host,omitempty"`
	Port          int32                  `protobuf:"varint,5,opt,name=port,proto3" json:"port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentRegistration) Reset() {
	*x = AgentRegistration{}
	mi := &file_proto_paddy_agents_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentRegistration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentRegistration) ProtoMessage() {}

func (x *AgentRegistration) ProtoReflect() protoreflect.Message {
	mi := &file_proto_paddy_agents_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentRegistration.ProtoReflect.Descriptor instead.
func (*AgentRegistration) Descriptor() ([]byte, []int) {
	return file_proto_paddy_agents_proto_rawDescGZIP(), []int{0}
}

func (x *AgentRegistration) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *AgentRegistration) GetAgentName() string {
	if x != nil {
		return x.AgentName
	}
	return ""
}

func (x *AgentRegistration) GetAgentType() string {
	if x != nil {
		return x.AgentType
	}
	return ""
}

func (x *AgentRegistration) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *AgentRegistration) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

type RegistrationAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegistrationAck) Reset() {
	*x = RegistrationAck{}
	mi := &file_proto_paddy_agents_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegistrationAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistrationAck) ProtoMessage() {}

func (x *RegistrationAck) ProtoReflect() protoreflect.Message {
	mi := &file_proto_paddy_agents_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistrationAck.ProtoReflect.Descriptor instead.
func (*RegistrationAck) Descriptor() ([]byte, []int) {
	return file_proto_paddy_agents_proto_rawDescGZIP(), []int{1}
}

func (x *RegistrationAck) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegistrationAck) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_proto_paddy_agents_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_paddy_agents_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_paddy_agents_proto_rawDescGZIP(), []int{2}
}

type SystemStatusResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	OrchestratorStatus  string                 `protobuf:"bytes,1,opt,name=orchestrator_status,json=orchestratorStatus,proto3" json:"orchestrator_status,omitempty"`
	ActiveAgents        []string               `protobuf:"bytes,2,rep,name=active_agents,json=activeAgents,proto3" json:"active_agents,omitempty"`
	TotalQueriesHandled int32                  `protobuf:"varint,3,opt,name=total_queries_handled,json=totalQueriesHandled,proto3" json:"total_queries_handled,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *SystemStatusResponse) Reset() {
	*x = SystemStatusResponse{}
	mi := &file_proto_paddy_agents_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemStatusResponse) ProtoMessage() {}

func (x *SystemStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_paddy_agents_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemStatusResponse.ProtoReflect.Descriptor instead.
func (*SystemStatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_paddy_agents_proto_rawDescGZIP(), []int{3}
}

func (x *SystemStatusResponse) GetOrchestratorStatus() string {
	if x != nil {
		return x.OrchestratorStatus
	}
	return ""
}

func (x *SystemStatusResponse) GetActiveAgents() []string {
	if x != nil {
		return x.ActiveAgents
	}
	return nil
}

func (x *SystemStatusResponse) GetTotalQueriesHandled() int32 {
	if x != nil {
		return x.TotalQueriesHandled
	}
	return 0
}

type FarmerQuery struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QueryId       string                 `protobuf:"bytes,1,opt,name=query_id,json=queryId,proto3" json:"query_id,omitempty"`
	QueryType     string                 `protobuf:"bytes,2,opt,name=query_type,json=queryType,proto3" json:"query_type,omitempty"` // "WEATHER" | "SOIL" | "CROP_HEALTH" | "FERTILIZER" | "MARKET" | "PEST_RISK" | "FULL"
	District      string                 `protobuf:"bytes,3,opt,name=district,proto3" json:"district,omitempty"`
	FarmerId      string                 `protobuf:"bytes,4,opt,name=farmer_id,json=farmerId,proto3" json:"farmer_id,omitempty"`
	Season        string                 `protobuf:"bytes,5,opt,name=season,proto3" json:"season,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FarmerQuery) Reset() {
	*x = FarmerQuery{}
	mi := &file_proto_paddy_agents_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FarmerQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FarmerQuery) ProtoMessage() {}

func (x *FarmerQuery) ProtoReflect() protoreflect.Message {
	mi := &file_proto_paddy_agents_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FarmerQuery.ProtoReflect.Descriptor instead.
func (*FarmerQuery) Descriptor() ([]byte, []int) {
	return file_proto_paddy_agents_proto_rawDescGZIP(), []int{4}
}

func (x *FarmerQuery) GetQueryId() string {
	if x != nil {
		return x.QueryId
	}
	return ""
}

func (x *FarmerQuery) GetQueryType() string {
	if x != nil {
		return x.QueryType
	}
	return ""
}

func (x *FarmerQuery) GetDistrict() string {
	if x != nil {
		return x.District
	}
	return ""
}

func (x *FarmerQuery) GetFarmerId() string {
	if x != nil {
		return x.FarmerId
	}
	return ""
}

func (x *FarmerQuery) GetSeason() string {
	if x != nil {
		return x.Season
	}
	return ""
}

type AgentResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentName     string                 `protobuf:"bytes,1,opt,name=agent_name,json=agentName,proto3" json:"agent_name,omitempty"`
	ResultJson    string                 `protobuf:"bytes,2,opt,name=result_json,json=resultJson,proto3" json:"result_json,omitempty"`
	Confidence    float32                `protobuf:"fixed32,3,opt,name=confidence,proto3" json:"confidence,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"` // "OK" | "ERROR" | "UNKNOWN_AGENT"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentResult) Reset() {
	*x = AgentResult{}
	mi := &file_proto_paddy_agents_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentResult) ProtoMessage() {}

func (x *AgentResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_paddy_agents_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentResult.ProtoReflect.Descriptor instead.
func (*AgentResult) Descriptor() ([]byte, []int) {
	return file_proto_paddy_agents_proto_rawDescGZIP(), []int{5}
}

func (x *AgentResult) GetAgentName() string {
	if x != nil {
		return x.AgentName
	}
	return ""
}

func (x *AgentResult) GetResultJson() string {
	if x != nil {
		return x.ResultJson
	}
	return ""
}

func (x *AgentResult) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *AgentResult) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type OrchestratorResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	QueryId           string                 `protobuf:"bytes,1,opt,name=query_id,json=queryId,proto3" json:"query_id,omitempty"`
	Recommendation    string                 `protobuf:"bytes,2,opt,name=recommendation,proto3" json:"recommendation,omitempty"`
	AgentResults      []*AgentResult         `protobuf:"bytes,3,rep,name=agent_results,json=agentResults,proto3" json:"agent_results,omitempty"`
	OverallConfidence float32                `protobuf:"fixed32,4,opt,name=overall_confidence,json=overallConfidence,proto3" json:"overall_confidence,omitempty"`
	Timestamp         string                 `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *OrchestratorResponse) Reset() {
	*x = OrchestratorResponse{}
	mi := &file_proto_paddy_agents_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrchestratorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrchestratorResponse) ProtoMessage() {}

func (x *OrchestratorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_paddy_agents_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrchestratorResponse.ProtoReflect.Descriptor instead.
func (*OrchestratorResponse) Descriptor() ([]byte, []int) {
	return file_proto_paddy_agents_proto_rawDescGZIP(), []int{6}
}

func (x *OrchestratorResponse) GetQueryId() string {
	if x != nil {
		return x.QueryId
	}
	return ""
}

func (x *OrchestratorResponse) GetRecommendation() string {
	if x != nil {
		return x.Recommendation
	}
	return ""
}

func (x *OrchestratorResponse) GetAgentResults() []*AgentResult {
	if x != nil {
		return x.AgentResults
	}
	return nil
}

func (x *OrchestratorResponse) GetOverallConfidence() float32 {
	if x != nil {
		return x.OverallConfidence
	}
	return 0
}

func (x *OrchestratorResponse) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

// ══════════════════════════════════════════════════════
// SHARED
// ══════════════════════════════════════════════════════
type AgentMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	AgentName     string                 `protobuf:"bytes,2,opt,name=agent_name,json=agentName,proto3" json:"agent_name,omitempty"`
	Timestamp     string                 `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Confidence    float32                `protobuf:"fixed32,4,opt,name=confidence,proto3" json:"confidence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentMetadata) Reset() {
	*x = AgentMetadata{}
	mi := &file_proto_paddy_agents_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentMetadata) ProtoMessage() {}

func (x *AgentMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_proto_paddy_agents_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentMetadata.ProtoReflect.Descriptor instead.
func (*AgentMetadata) Descriptor() ([]byte, []int) {
	return file_proto_paddy_agents_proto_rawDescGZIP(), []int{7}
}

func (x *AgentMetadata) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *AgentMetadata) GetAgentName() string {
	if x != nil {
		return x.AgentName
	}
	return ""
}

func (x *AgentMetadata) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *AgentMetadata) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

type WeatherRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	District      string                 `protobuf:"bytes,1,opt,name=district,proto3" json:"district,omitempty"`
	Date          string                 `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"`
	ForecastDays  int32                  `protobuf:"varint,3,opt,name=forecast_days,json=forecastDays,proto3" json:"forecast_days,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WeatherRequest) Reset() {
	*x = WeatherRequest{}
	mi := &file_proto_paddy_agents_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WeatherRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WeatherRequest) ProtoMessage() {}

func (x *WeatherRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_paddy_agents_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WeatherRequest.ProtoReflect.Descriptor instead.
func (*WeatherRequest) Descriptor() ([]byte, []int) {
	return file_proto_paddy_agents_proto_rawDescGZIP(), []int{8}
}

func (x *WeatherRequest) GetDistrict() string {
	if x != nil {
		return x.District
	}
	return ""
}

func (x *WeatherRequest) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *WeatherRequest) GetForecastDays() int32 {
	if x != nil {
		return x.ForecastDays
	}
	return 0
}

type DailyForecast struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Date          string                 `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	TempMax       float32                `protobuf:"fixed32,2,opt,name=temp_max,json=tempMax,proto3" json:"temp_max,omitempty"`
	TempMin       float32                `protobuf:"fixed32,3,opt,name=temp_min,json=tempMin,proto3" json:"temp_min,omitempty"`
	RainfallProb  float32                `protobuf:"fixed32,4,opt,name=rainfall_prob,json=rainfallProb,proto3" json:"rainfall_prob,omitempty"`
	Condition     string                 `protobuf:"bytes,5,opt,name=condition,proto3" json:"condition,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DailyForecast) Reset() {
	*x = DailyForecast{}
	mi := &file_proto_paddy_agents_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DailyForecast) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DailyForecast) ProtoMessage() {}

func (x *DailyForecast) ProtoReflect() protoreflect.Message {
	mi := &file_proto_paddy_agents_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DailyForecast.ProtoReflect.Descriptor instead.
func (*DailyForecast) Descriptor() ([]byte, []int) {
	return file_proto_paddy_agents_proto_rawDescGZIP(), []int{9}
}

func (x *DailyForecast) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *DailyForecast) GetTempMax() float32 {
	if x != nil {
		return x.TempMax
	}
	return 0
}

func (x *DailyForecast) GetTempMin() float32 {
	if x != nil {
		return x.TempMin
	}
	return 0
}

func (x *DailyForecast) GetRainfallProb() float32 {
	if x != nil {
		return x.RainfallProb
	}
	return 0
}

func (x *DailyForecast) GetCondition() string {
	if x != nil {
		return x.Condition
	}
	return ""
}

type WeatherResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Metadata         *AgentMetadata         `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	District         string                 `protobuf:"bytes,2,opt,name=district,proto3" json:"district,omitempty"`
	TemperatureMax   float32                `protobuf:"fixed32,3,opt,name=temperature_max,json=temperatureMax,proto3" json:"temperature_max,omitempty"`
	TemperatureMin   float32                `protobuf:"fixed32,4,opt,name=temperature_min,json=temperatureMin,proto3" json:"temperature_min,omitempty"`
	TemperatureAvg   float32                `protobuf:"fixed32,5,opt,name=temperature_avg,json=temperatureAvg,proto3" json:"temperature_avg,omitempty"`
	RainfallMm       float32                `protobuf:"fixed32,6,opt,name=rainfall_mm,json=rainfallMm,proto3" json:"rainfall_mm,omitempty"`
	HumidityPercent  float32                `protobuf:"fixed32,7,opt,name=humidity_percent,json=humidityPercent,proto3" json:"humidity_percent,omitempty"`
	WindSpeedKmph    float32                `protobuf:"fixed32,8,opt,name=wind_speed_kmph,json=windSpeedKmph,proto3" json:"wind_speed_kmph,omitempty"`
	SunshineHours    float32                `protobuf:"fixed32,9,opt,name=sunshine_hours,json=sunshineHours,proto3" json:"sunshine_hours,omitempty"`
	WeatherCondition string                 `protobuf:"bytes,10,opt,name=weather_condition,json=weatherCondition,proto3" json:"weather_condition,omitempty"`
	FarmingAdvisory  string                 `protobuf:"bytes,11,opt,name=farming_advisory,json=farmingAdvisory,proto3" json:"farming_advisory,omitempty"`
	Forecast         []*DailyForecast       `protobuf:"bytes,12,rep,name=forecast,proto3" json:"forecast,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *WeatherResponse) Reset() {
	*x = WeatherResponse{}
	mi := &file_proto_paddy_agents_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WeatherResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WeatherResponse) ProtoMessage() {}

func (x *WeatherResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_paddy_agents_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WeatherResponse.ProtoReflect.Descriptor instead.
func (*WeatherResponse) Descriptor() ([]byte, []int) {
	return file_proto_paddy_agents_proto_rawDescGZIP(), []int{10}
}

func (x *WeatherResponse) GetMetadata() *AgentMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *WeatherResponse) GetDistrict() string {
	if x != nil {
		return x.District
	}
	return ""
}

func (x *WeatherResponse) GetTemperatureMax() float32 {
	if x != nil {
		return x.TemperatureMax
	}
	return 0
}

func (x *WeatherResponse) GetTemperatureMin() float32 {
	if x != nil {
		return x.TemperatureMin
	}
	return 0
}

func (x *WeatherResponse) GetTemperatureAvg() float32 {
	if x != nil {
		return x.TemperatureAvg
	}
	return 0
}

func (x *WeatherResponse) GetRainfallMm() float32 {
	if x != nil {
		return x.RainfallMm
	}
	return 0
}

func (x *WeatherResponse) GetHumidityPercent() float32 {
	if x != nil {
		return x.HumidityPercent
	}
	return 0
}

func (x *WeatherResponse) GetWindSpeedKmph() float32 {
	if x != nil {
		return x.WindSpeedKmph
	}
	return 0
}

func (x *WeatherResponse) GetSunshineHours() float32 {
	if x != nil {
		return x.SunshineHours
	}
	return 0
}

func (x *WeatherResponse) GetWeatherCondition() string {
	if x != nil {
		return x.WeatherCondition
	}
	return ""
}

func (x *WeatherResponse) GetFarmingAdvisory() string {
	if x != nil {
		return x.FarmingAdvisory
	}
	return ""
}

func (x *WeatherResponse) GetForecast() []*DailyForecast {
	if x != nil {
		return x.Forecast
	}
	return nil
}

type WeatherAlertResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Metadata       *AgentMetadata         `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	HasAlert       bool                   `protobuf:"varint,2,opt,name=has_alert,json=hasAlert,proto3" json:"has_alert,omitempty"`
	AlertType      string                 `protobuf:"bytes,3,opt,name=alert_type,json=alertType,proto3" json:"alert_type,omitempty"`
	Severity       string                 `protobuf:"bytes,4,opt,name=severity,proto3" json:"severity,omitempty"`
	Message        string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	ActionRequired string                 `protobuf:"bytes,6,opt,name=action_required,json=actionRequired,proto3" json:"action_required,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *WeatherAlertResponse) Reset() {
	*x = WeatherAlertResponse{}
	mi := &file_proto_paddy_agents_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WeatherAlertResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WeatherAlertResponse) ProtoMessage() {}

func (x *WeatherAlertResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_paddy_agents_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WeatherAlertResponse.ProtoReflect.Descriptor instead.
func (*WeatherAlertResponse) Descriptor() ([]byte, []int) {
	return file_proto_paddy_agents_proto_rawDescGZIP(), []int{11}
}

func (x *WeatherAlertResponse) GetMetadata() *AgentMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *WeatherAlertResponse) GetHasAlert() bool {
	if x != nil {
		return x.HasAlert
	}
	return false
}

func (x *WeatherAlertResponse) GetAlertType() string {
	if x != nil {
		return x.AlertType
	}
	return ""
}

func (x *WeatherAlertResponse) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *WeatherAlertResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *WeatherAlertResponse) GetActionRequired() string {
	if x != nil {
		return x.ActionRequired
	}
	return ""
}

type HistoricalWeatherReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	District      string                 `protobuf:"bytes,1,opt,name=district,proto3" json:"district,omitempty"`
	StartDate     string                 `protobuf:"bytes,2,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       string                 `protobuf:"bytes,3,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HistoricalWeatherReq) Reset() {
	*x = HistoricalWeatherReq{}
	mi := &file_proto_paddy_agents_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HistoricalWeatherReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistoricalWeatherReq) ProtoMessage() {}

func (x *HistoricalWeatherReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_paddy_agents_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistoricalWeatherReq.ProtoReflect.Descriptor instead.
func (*HistoricalWeatherReq) Descriptor() ([]byte, []int) {
	return file_proto_paddy_agents_proto_rawDescGZIP(), []int{12}
}

func (x *HistoricalWeatherReq) GetDistrict() string {
	if x != nil {
		return x.District
	}
	return ""
}

func (x *HistoricalWeatherReq) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *HistoricalWeatherReq) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

type HistoricalWeatherResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *AgentMetadata         `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Records       []*WeatherResponse     `protobuf:"bytes,2,rep,name=records,proto3" json:"records,omitempty"`
	AvgTemp       float32                `protobuf:"fixed32,3,opt,name=avg_temp,json=avgTemp,proto3" json:"avg_temp,omitempty"`
	TotalRainfall float32                `protobuf:"fixed32,4,opt,name=total_rainfall,json=totalRainfall,proto3" json:"total_rainfall,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HistoricalWeatherResp) Reset() {
	*x = HistoricalWeatherResp{}
	mi := &file_proto_paddy_agents_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HistoricalWeatherResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistoricalWeatherResp) ProtoMessage() {}

func (x *HistoricalWeatherResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_paddy_agents_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistoricalWeatherResp.ProtoReflect.Descriptor instead.
func (*HistoricalWeatherResp) Descriptor() ([]byte, []int) {
	return file_proto_paddy_agents_proto_rawDescGZIP(), []int{13}
}

func (x *HistoricalWeatherResp) GetMetadata() *AgentMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *HistoricalWeatherResp) GetRecords() []*WeatherResponse {
	if x != nil {
		return x.Records
	}
	return nil
}

func (x *HistoricalWeatherResp) GetAvgTemp() float32 {
	if x != nil {
		return x.AvgTemp
	}
	return 0
}

func (x *HistoricalWeatherResp) GetTotalRainfall() float32 {
	if x != nil {
		return x.TotalRainfall
	}
	return 0
}

type SoilRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	District      string                 `protobuf:"bytes,1,opt,name=district,proto3" json:"district,omitempty"`
	Season        string                 `protobuf:"bytes,2,opt,name=season,proto3" json:"season,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SoilRequest) Reset() {
	*x = SoilRequest{}
	mi := &file_proto_paddy_agents_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SoilRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SoilRequest) ProtoMessage() {}

func (x *SoilRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_paddy_agents_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SoilRequest.ProtoReflect.Descriptor instead.
func (*SoilRequest) Descriptor() ([]byte, []int) {
	return file_proto_paddy_agents_proto_rawDescGZIP(), []int{14}
}

func (x *SoilRequest) GetDistrict() string {
	if x != nil {
		return x.District
	}
	return ""
}

func (x *SoilRequest) GetSeason() string {
	if x != nil {
		return x.Season
	}
	return ""
}

type SoilResponse struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Metadata *AgentMetadata         `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	District string                 `protobuf:"bytes,2,opt,name=district,proto3" json:"district,omitempty"`
	// NPK profile
	Nitrogen   float32 `protobuf:"fixed32,3,opt,name=nitrogen,proto3" json:"nitrogen,omitempty"`
	Phosphorus float32 `protobuf:"fixed32,4,opt,name=phosphorus,proto3" json:"phosphorus,omitempty"`
	Potassium  float32 `protobuf:"fixed32,5,opt,name=potassium,proto3" json:"potassium,omitempty"`
	// Soil chemistry
	Ph            float32 `protobuf:"fixed32,6,opt,name=ph,proto3" json:"ph,omitempty"`
	OrganicCarbon float32 `protobuf:"fixed32,7,opt,name=organic_carbon,json=organicCarbon,proto3" json:"organic_carbon,omitempty"`
	// Fertilizer advisory (KVK rules)
	UreaKgPerHa   float32 `protobuf:"fixed32,8,opt,name=urea_kg_per_ha,json=ureaKgPerHa,proto3" json:"urea_kg_per_ha,omitempty"`
	DapKgPerHa    float32 `protobuf:"fixed32,9,opt,name=dap_kg_per_ha,json=dapKgPerHa,proto3" json:"dap_kg_per_ha,omitempty"`
	PotashKgPerHa float32 `protobuf:"fixed32,10,opt,name=potash_kg_per_ha,json=potashKgPerHa,proto3" json:"potash_kg_per_ha,omitempty"`
	TimingAdvice  string  `protobuf:"bytes,11,opt,name=timing_advice,json=timingAdvice,proto3" json:"timing_advice,omitempty"`
	// Yield prediction (RF model)
	PredictedYieldKgPerHa float32 `protobuf:"fixed32,12,opt,name=predicted_yield_kg_per_ha,json=predictedYieldKgPerHa,proto3" json:"predicted_yield_kg_per_ha,omitempty"`
	YieldInterpretation   string  `protobuf:"bytes,13,opt,name=yield_interpretation,json=yieldInterpretation,proto3" json:"yield_interpretation,omitempty"`
	// 15-year soil trend
	PhTrendSlope        float32 `protobuf:"fixed32,14,opt,name=ph_trend_slope,json=phTrendSlope,proto3" json:"ph_trend_slope,omitempty"`
	OcTrendSlope        float32 `protobuf:"fixed32,15,opt,name=oc_trend_slope,json=ocTrendSlope,proto3" json:"oc_trend_slope,omitempty"`
	TrendInterpretation string  `protobuf:"bytes,16,opt,name=trend_interpretation,json=trendInterpretation,proto3" json:"trend_interpretation,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *SoilResponse) Reset() {
	*x = SoilResponse{}
	mi := &file_proto_paddy_agents_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SoilResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SoilResponse) ProtoMessage() {}

func (x *SoilResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_paddy_agents_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SoilResponse.ProtoReflect.Descriptor instead.
func (*SoilResponse) Descriptor() ([]byte, []int) {
	return file_proto_paddy_agents_proto_rawDescGZIP(), []int{15}
}

func (x *SoilResponse) GetMetadata() *AgentMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *SoilResponse) GetDistrict() string {
	if x != nil {
		return x.District
	}
	return ""
}

func (x *SoilResponse) GetNitrogen() float32 {
	if x != nil {
		return x.Nitrogen
	}
	return 0
}

func (x *SoilResponse) GetPhosphorus() float32 {
	if x != nil {
		return x.Phosphorus
	}
	return 0
}

func (x *SoilResponse) GetPotassium() float32 {
	if x != nil {
		return x.Potassium
	}
	return 0
}

func (x *SoilResponse) GetPh() float32 {
	if x != nil {
		return x.Ph
	}
	return 0
}

func (x *SoilResponse) GetOrganicCarbon() float32 {
	if x != nil {
		return x.OrganicCarbon
	}
	return 0
}

func (x *SoilResponse) GetUreaKgPerHa() float32 {
	if x != nil {
		return x.UreaKgPerHa
	}
	return 0
}

func (x *SoilResponse) GetDapKgPerHa() float32 {
	if x != nil {
		return x.DapKgPerHa
	}
	return 0
}

func (x *SoilResponse) GetPotashKgPerHa() float32 {
	if x != nil {
		return x.PotashKgPerHa
	}
	return 0
}

func (x *SoilResponse) GetTimingAdvice() string {
	if x != nil {
		return x.TimingAdvice
	}
	return ""
}

func (x *SoilResponse) GetPredictedYieldKgPerHa() float32 {
	if x != nil {
		return x.PredictedYieldKgPerHa
	}
	return 0
}

func (x *SoilResponse) GetYieldInterpretation() string {
	if x != nil {
		return x.YieldInterpretation
	}
	return ""
}

func (x *SoilResponse) GetPhTrendSlope() float32 {
	if x != nil {
		return x.PhTrendSlope
	}
	return 0
}

func (x *SoilResponse) GetOcTrendSlope() float32 {
	if x != nil {
		return x.OcTrendSlope
	}
	return 0
}

func (x *SoilResponse) GetTrendInterpretation() string {
	if x != nil {
		return x.TrendInterpretation
	}
	return ""
}

type CropHealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	District      string                 `protobuf:"bytes,1,opt,name=district,proto3" json:"district,omitempty"`
	Season        string                 `protobuf:"bytes,2,opt,name=season,proto3" json:"season,omitempty"`
	Year          int32                  `protobuf:"varint,3,opt,name=year,proto3" json:"year,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CropHealthRequest) Reset() {
	*x = CropHealthRequest{}
	mi := &file_proto_paddy_agents_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CropHealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CropHealthRequest) ProtoMessage() {}

func (x *CropHealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_paddy_agents_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CropHealthRequest.ProtoReflect.Descriptor instead.
func (*CropHealthRequest) Descriptor() ([]byte, []int) {
	return file_proto_paddy_agents_proto_rawDescGZIP(), []int{16}
}

func (x *CropHealthRequest) GetDistrict() string {
	if x != nil {
		return x.District
	}
	return ""
}

func (x *CropHealthRequest) GetSeason() string {
	if x != nil {
		return x.Season
	}
	return ""
}

func (x *CropHealthRequest) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

type CropHealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *AgentMetadata         `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	District      string                 `protobuf:"bytes,2,opt,name=district,proto3" json:"district,omitempty"`
	StressClass   string                 `protobuf:"bytes,3,opt,name=stress_class,json=stressClass,proto3" json:"stress_class,omitempty"` // "Healthy" | "Mild" | "Moderate" | "Severe"
	NdviDeviation float32                `protobuf:"fixed32,4,opt,name=ndvi_deviation,json=ndviDeviation,proto3" json:"ndvi_deviation,omitempty"`
	GrowthStage   string                 `protobuf:"bytes,5,opt,name=growth_stage,json=growthStage,proto3" json:"growth_stage,omitempty"`
	Treatment     string                 `protobuf:"bytes,6,opt,name=treatment,proto3" json:"treatment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CropHealthResponse) Reset() {
	*x = CropHealthResponse{}
	mi := &file_proto_paddy_agents_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CropHealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CropHealthResponse) ProtoMessage() {}

func (x *CropHealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_paddy_agents_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CropHealthResponse.ProtoReflect.Descriptor instead.
func (*CropHealthResponse) Descriptor() ([]byte, []int) {
	return file_proto_paddy_agents_proto_rawDescGZIP(), []int{17}
}

func (x *CropHealthResponse) GetMetadata() *AgentMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *CropHealthResponse) GetDistrict() string {
	if x != nil {
		return x.District
	}
	return ""
}

func (x *CropHealthResponse) GetStressClass() string {
	if x != nil {
		return x.StressClass
	}
	return ""
}

func (x *CropHealthResponse) GetNdviDeviation() float32 {
	if x != nil {
		return x.NdviDeviation
	}
	return 0
}

func (x *CropHealthResponse) GetGrowthStage() string {
	if x != nil {
		return x.GrowthStage
	}
	return ""
}

func (x *CropHealthResponse) GetTreatment() string {
	if x != nil {
		return x.Treatment
	}
	return ""
}

type MarketRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	District      string                 `protobuf:"bytes,1,opt,name=district,proto3" json:"district,omitempty"`
	Crop          string                 `protobuf:"bytes,2,opt,name=crop,proto3" json:"crop,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarketRequest) Reset() {
	*x = MarketRequest{}
	mi := &file_proto_paddy_agents_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarketRequest) ProtoMessage() {}

func (x *MarketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_paddy_agents_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarketRequest.ProtoReflect.Descriptor instead.
func (*MarketRequest) Descriptor() ([]byte, []int) {
	return file_proto_paddy_agents_proto_rawDescGZIP(), []int{18}
}

func (x *MarketRequest) GetDistrict() string {
	if x != nil {
		return x.District
	}
	return ""
}

func (x *MarketRequest) GetCrop() string {
	if x != nil {
		return x.Crop
	}
	return ""
}

type MarketResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *AgentMetadata         `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	District      string                 `protobuf:"bytes,2,opt,name=district,proto3" json:"district,omitempty"`
	CurrentPrice  float32                `protobuf:"fixed32,3,opt,name=current_price,json=currentPrice,proto3" json:"current_price,omitempty"`
	Avg_30Day     float32                `protobuf:"fixed32,4,opt,name=avg_30day,json=avg30day,proto3" json:"avg_30day,omitempty"`
	Avg_90Day     float32                `protobuf:"fixed32,5,opt,name=avg_90day,json=avg90day,proto3" json:"avg_90day,omitempty"`
	PriceTrend    string                 `protobuf:"bytes,6,opt,name=price_trend,json=priceTrend,proto3" json:"price_trend,omitempty"` // "rising" | "falling" | "stable"
	BestMonth     string                 `protobuf:"bytes,7,opt,name=best_month,json=bestMonth,proto3" json:"best_month,omitempty"`
	Advisory      string                 `protobuf:"bytes,8,opt,name=advisory,proto3" json:"advisory,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarketResponse) Reset() {
	*x = MarketResponse{}
	mi := &file_proto_paddy_agents_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarketResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarketResponse) ProtoMessage() {}

func (x *MarketResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_paddy_agents_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarketResponse.ProtoReflect.Descriptor instead.
func (*MarketResponse) Descriptor() ([]byte, []int) {
	return file_proto_paddy_agents_proto_rawDescGZIP(), []int{19}
}

func (x *MarketResponse) GetMetadata() *AgentMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *MarketResponse) GetDistrict() string {
	if x != nil {
		return x.District
	}
	return ""
}

func (x *MarketResponse) GetCurrentPrice() float32 {
	if x != nil {
		return x.CurrentPrice
	}
	return 0
}

func (x *MarketResponse) GetAvg_30Day() float32 {
	if x != nil {
		return x.Avg_30Day
	}
	return 0
}

func (x *MarketResponse) GetAvg_90Day() float32 {
	if x != nil {
		return x.Avg_90Day
	}
	return 0
}

func (x *MarketResponse) GetPriceTrend() string {
	if x != nil {
		return x.PriceTrend
	}
	return ""
}

func (x *MarketResponse) GetBestMonth() string {
	if x != nil {
		return x.BestMonth
	}
	return ""
}

func (x *MarketResponse) GetAdvisory() string {
	if x != nil {
		return x.Advisory
	}
	return ""
}

type PestRiskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	District      string                 `protobuf:"bytes,1,opt,name=district,proto3" json:"district,omitempty"`
	Season        string                 `protobuf:"bytes,2,opt,name=season,proto3" json:"season,omitempty"`
	GrowthStage   string                 `protobuf:"bytes,3,opt,name=growth_stage,json=growthStage,proto3" json:"growth_stage,omitempty"`
	Temperature   float32                `protobuf:"fixed32,4,opt,name=temperature,proto3" json:"temperature,omitempty"`
	Humidity      float32                `protobuf:"fixed32,5,opt,name=humidity,proto3" json:"humidity,omitempty"`
	Rainfall      float32                `protobuf:"fixed32,6,opt,name=rainfall,proto3" json:"rainfall,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PestRiskRequest) Reset() {
	*x = PestRiskRequest{}
	mi := &file_proto_paddy_agents_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PestRiskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PestRiskRequest) ProtoMessage() {}

func (x *PestRiskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_paddy_agents_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PestRiskRequest.ProtoReflect.Descriptor instead.
func (*PestRiskRequest) Descriptor() ([]byte, []int) {
	return file_proto_paddy_agents_proto_rawDescGZIP(), []int{20}
}

func (x *PestRiskRequest) GetDistrict() string {
	if x != nil {
		return x.District
	}
	return ""
}

func (x *PestRiskRequest) GetSeason() string {
	if x != nil {
		return x.Season
	}
	return ""
}

func (x *PestRiskRequest) GetGrowthStage() string {
	if x != nil {
		return x.GrowthStage
	}
	return ""
}

func (x *PestRiskRequest) GetTemperature() float32 {
	if x != nil {
		return x.Temperature
	}
	return 0
}

func (x *PestRiskRequest) GetHumidity() float32 {
	if x != nil {
		return x.Humidity
	}
	return 0
}

func (x *PestRiskRequest) GetRainfall() float32 {
	if x != nil {
		return x.Rainfall
	}
	return 0
}

type PestInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	RiskLevel     string                 `protobuf:"bytes,2,opt,name=risk_level,json=riskLevel,proto3" json:"risk_level,omitempty"`
	Signs         string                 `protobuf:"bytes,3,opt,name=signs,proto3" json:"signs,omitempty"`
	Action        string                 `protobuf:"bytes,4,opt,name=action,proto3" json:"action,omitempty"`
	EtlThreshold  string                 `protobuf:"bytes,5,opt,name=etl_threshold,json=etlThreshold,proto3" json:"etl_threshold,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PestInfo) Reset() {
	*x = PestInfo{}
	mi := &file_proto_paddy_agents_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PestInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PestInfo) ProtoMessage() {}

func (x *PestInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_paddy_agents_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PestInfo.ProtoReflect.Descriptor instead.
func (*PestInfo) Descriptor() ([]byte, []int) {
	return file_proto_paddy_agents_proto_rawDescGZIP(), []int{21}
}

func (x *PestInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PestInfo) GetRiskLevel() string {
	if x != nil {
		return x.RiskLevel
	}
	return ""
}

func (x *PestInfo) GetSigns() string {
	if x != nil {
		return x.Signs
	}
	return ""
}

func (x *PestInfo) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *PestInfo) GetEtlThreshold() string {
	if x != nil {
		return x.EtlThreshold
	}
	return ""
}

type PestRiskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *AgentMetadata         `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	District      string                 `protobuf:"bytes,2,opt,name=district,proto3" json:"district,omitempty"`
	OverallRisk   string                 `protobuf:"bytes,3,opt,name=overall_risk,json=overallRisk,proto3" json:"overall_risk,omitempty"` // "Low" | "Medium" | "High"
	Pests         []*PestInfo            `protobuf:"bytes,4,rep,name=pests,proto3" json:"pests,omitempty"`
	Advisory      string                 `protobuf:"bytes,5,opt,name=advisory,proto3" json:"advisory,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PestRiskResponse) Reset() {
	*x = PestRiskResponse{}
	mi := &file_proto_paddy_agents_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PestRiskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PestRiskResponse) ProtoMessage() {}

func (x *PestRiskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_paddy_agents_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PestRiskResponse.ProtoReflect.Descriptor instead.
func (*PestRiskResponse) Descriptor() ([]byte, []int) {
	return file_proto_paddy_agents_proto_rawDescGZIP(), []int{22}
}

func (x *PestRiskResponse) GetMetadata() *AgentMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *PestRiskResponse) GetDistrict() string {
	if x != nil {
		return x.District
	}
	return ""
}

func (x *PestRiskResponse) GetOverallRisk() string {
	if x != nil {
		return x.OverallRisk
	}
	return ""
}

func (x *PestRiskResponse) GetPests() []*PestInfo {
	if x != nil {
		return x.Pests
	}
	return nil
}

func (x *PestRiskResponse) GetAdvisory() string {
	if x != nil {
		return x.Advisory
	}
	return ""
}

var File_proto_paddy_agents_proto protoreflect.FileDescriptor

const file_proto_paddy_agents_proto_rawDesc = "" +
	"\n" +
	"\x18proto/paddy_agents.proto\x12\x05paddy\"\x94\x01\n" +
	"\x11AgentRegistration\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1d\n" +
	"\n" +
	"agent_name\x18\x02 \x01(\tR\tagentName\x12\x1d\n" +
	"\n" +
	"agent_type\x18\x03 \x01(\tR\tagentType\x12\x12\n" +
	"\x04host\x18\x04 \x01(\tR\x04host\x12\x12\n" +
	"\x04port\x18\x05 \x01(\x05R\x04port\"E\n" +
	"\x0fRegistrationAck\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x0f\n" +
	"\rStatusRequest\"\xa0\x01\n" +
	"\x14SystemStatusResponse\x12/\n" +
	"\x13orchestrator_status\x18\x01 \x01(\tR\x12orchestratorStatus\x12#\n" +
	"\ractive_agents\x18\x02 \x03(\tR\factiveAgents\x122\n" +
	"\x15total_queries_handled\x18\x03 \x01(\x05R\x13totalQueriesHandled\"\x98\x01\n" +
	"\vFarmerQuery\x12\x19\n" +
	"\bquery_id\x18\x01 \x01(\tR\aqueryId\x12\x1d\n" +
	"\n" +
	"query_type\x18\x02 \x01(\tR\tqueryType\x12\x1a\n" +
	"\bdistrict\x18\x03 \x01(\tR\bdistrict\x12\x1b\n" +
	"\tfarmer_id\x18\x04 \x01(\tR\bfarmerId\x12\x16\n" +
	"\x06season\x18\x05 \x01(\tR\x06season\"\x85\x01\n" +
	"\vAgentResult\x12\x1d\n" +
	"\n" +
	"agent_name\x18\x01 \x01(\tR\tagentName\x12\x1f\n" +
	"\vresult_json\x18\x02 \x01(\tR\n" +
	"resultJson\x12\x1e\n" +
	"\n" +
	"confidence\x18\x03 \x01(\x02R\n" +
	"confidence\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\"\xdf\x01\n" +
	"\x14OrchestratorResponse\x12\x19\n" +
	"\bquery_id\x18\x01 \x01(\tR\aqueryId\x12&\n" +
	"\x0erecommendation\x18\x02 \x01(\tR\x0erecommendation\x127\n" +
	"\ragent_results\x18\x03 \x03(\v2\x12.paddy.AgentResultR\fagentResults\x12-\n" +
	"\x12overall_confidence\x18\x04 \x01(\x02R\x11overallConfidence\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\tR\ttimestamp\"\x87\x01\n" +
	"\rAgentMetadata\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1d\n" +
	"\n" +
	"agent_name\x18\x02 \x01(\tR\tagentName\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\tR\ttimestamp\x12\x1e\n" +
	"\n" +
	"confidence\x18\x04 \x01(\x02R\n" +
	"confidence\"e\n" +
	"\x0eWeatherRequest\x12\x1a\n" +
	"\bdistrict\x18\x01 \x01(\tR\bdistrict\x12\x12\n" +
	"\x04date\x18\x02 \x01(\tR\x04date\x12#\n" +
	"\rforecast_days\x18\x03 \x01(\x05R\fforecastDays\"\x9c\x01\n" +
	"\rDailyForecast\x12\x12\n" +
	"\x04date\x18\x01 \x01(\tR\x04date\x12\x19\n" +
	"\btemp_max\x18\x02 \x01(\x02R\atempMax\x12\x19\n" +
	"\btemp_min\x18\x03 \x01(\x02R\atempMin\x12#\n" +
	"\rrainfall_prob\x18\x04 \x01(\x02R\frainfallProb\x12\x1c\n" +
	"\tcondition\x18\x05 \x01(\tR\tcondition\"\xff\x03\n" +
	"\x0fWeatherResponse\x120\n" +
	"\bmetadata\x18\x01 \x01(\v2\x14.paddy.AgentMetadataR\bmetadata\x12\x1a\n" +
	"\bdistrict\x18\x02 \x01(\tR\bdistrict\x12'\n" +
	"\x0ftemperature_max\x18\x03 \x01(\x02R\x0etemperatureMax\x12'\n" +
	"\x0ftemperature_min\x18\x04 \x01(\x02R\x0etemperatureMin\x12'\n" +
	"\x0ftemperature_avg\x18\x05 \x01(\x02R\x0etemperatureAvg\x12\x1f\n" +
	"\vrainfall_mm\x18\x06 \x01(\x02R\n" +
	"rainfallMm\x12)\n" +
	"\x10humidity_percent\x18\a \x01(\x02R\x0fhumidityPercent\x12&\n" +
	"\x0fwind_speed_kmph\x18\b \x01(\x02R\rwindSpeedKmph\x12%\n" +
	"\x0esunshine_hours\x18\t \x01(\x02R\rsunshineHours\x12+\n" +
	"\x11weather_condition\x18\n" +
	" \x01(\tR\x10weatherCondition\x12)\n" +
	"\x10farming_advisory\x18\v \x01(\tR\x0ffarmingAdvisory\x120\n" +
	"\bforecast\x18\f \x03(\v2\x14.paddy.DailyForecastR\bforecast\"\xe3\x01\n" +
	"\x14WeatherAlertResponse\x120\n" +
	"\bmetadata\x18\x01 \x01(\v2\x14.paddy.AgentMetadataR\bmetadata\x12\x1b\n" +
	"\thas_alert\x18\x02 \x01(\bR\bhasAlert\x12\x1d\n" +
	"\n" +
	"alert_type\x18\x03 \x01(\tR\talertType\x12\x1a\n" +
	"\bseverity\x18\x04 \x01(\tR\bseverity\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\x12'\n" +
	"\x0faction_required\x18\x06 \x01(\tR\x0eactionRequired\"l\n" +
	"\x14HistoricalWeatherReq\x12\x1a\n" +
	"\bdistrict\x18\x01 \x01(\tR\bdistrict\x12\x1d\n" +
	"\n" +
	"start_date\x18\x02 \x01(\tR\tstartDate\x12\x19\n" +
	"\bend_date\x18\x03 \x01(\tR\aendDate\"\xbd\x01\n" +
	"\x15HistoricalWeatherResp\x120\n" +
	"\bmetadata\x18\x01 \x01(\v2\x14.paddy.AgentMetadataR\bmetadata\x120\n" +
	"\arecords\x18\x02 \x03(\v2\x16.paddy.WeatherResponseR\arecords\x12\x19\n" +
	"\bavg_temp\x18\x03 \x01(\x02R\aavgTemp\x12%\n" +
	"\x0etotal_rainfall\x18\x04 \x01(\x02R\rtotalRainfall\"A\n" +
	"\vSoilRequest\x12\x1a\n" +
	"\bdistrict\x18\x01 \x01(\tR\bdistrict\x12\x16\n" +
	"\x06season\x18\x02 \x01(\tR\x06season\"\xef\x04\n" +
	"\fSoilResponse\x120\n" +
	"\bmetadata\x18\x01 \x01(\v2\x14.paddy.AgentMetadataR\bmetadata\x12\x1a\n" +
	"\bdistrict\x18\x02 \x01(\tR\bdistrict\x12\x1a\n" +
	"\bnitrogen\x18\x03 \x01(\x02R\bnitrogen\x12\x1e\n" +
	"\n" +
	"phosphorus\x18\x04 \x01(\x02R\n" +
	"phosphorus\x12\x1c\n" +
	"\tpotassium\x18\x05 \x01(\x02R\tpotassium\x12\x0e\n" +
	"\x02ph\x18\x06 \x01(\x02R\x02ph\x12%\n" +
	"\x0eorganic_carbon\x18\a \x01(\x02R\rorganicCarbon\x12#\n" +
	"\x0eurea_kg_per_ha\x18\b \x01(\x02R\vureaKgPerHa\x12!\n" +
	"\rdap_kg_per_ha\x18\t \x01(\x02R\n" +
	"dapKgPerHa\x12'\n" +
	"\x10potash_kg_per_ha\x18\n" +
	" \x01(\x02R\rpotashKgPerHa\x12#\n" +
	"\rtiming_advice\x18\v \x01(\tR\ftimingAdvice\x128\n" +
	"\x19predicted_yield_kg_per_ha\x18\f \x01(\x02R\x15predictedYieldKgPerHa\x121\n" +
	"\x14yield_interpretation\x18\r \x01(\tR\x13yieldInterpretation\x12$\n" +
	"\x0eph_trend_slope\x18\x0e \x01(\x02R\fphTrendSlope\x12$\n" +
	"\x0eoc_trend_slope\x18\x0f \x01(\x02R\focTrendSlope\x121\n" +
	"\x14trend_interpretation\x18\x10 \x01(\tR\x13trendInterpretation\"[\n" +
	"\x11CropHealthRequest\x12\x1a\n" +
	"\bdistrict\x18\x01 \x01(\tR\bdistrict\x12\x16\n" +
	"\x06season\x18\x02 \x01(\tR\x06season\x12\x12\n" +
	"\x04year\x18\x03 \x01(\x05R\x04year\"\xed\x01\n" +
	"\x12CropHealthResponse\x120\n" +
	"\bmetadata\x18\x01 \x01(\v2\x14.paddy.AgentMetadataR\bmetadata\x12\x1a\n" +
	"\bdistrict\x18\x02 \x01(\tR\bdistrict\x12!\n" +
	"\fstress_class\x18\x03 \x01(\tR\vstressClass\x12%\n" +
	"\x0endvi_deviation\x18\x04 \x01(\x02R\rndviDeviation\x12!\n" +
	"\fgrowth_stage\x18\x05 \x01(\tR\vgrowthStage\x12\x1c\n" +
	"\ttreatment\x18\x06 \x01(\tR\ttreatment\"?\n" +
	"\rMarketRequest\x12\x1a\n" +
	"\bdistrict\x18\x01 \x01(\tR\bdistrict\x12\x12\n" +
	"\x04crop\x18\x02 \x01(\tR\x04crop\"\x99\x02\n" +
	"\x0eMarketResponse\x120\n" +
	"\bmetadata\x18\x01 \x01(\v2\x14.paddy.AgentMetadataR\bmetadata\x12\x1a\n" +
	"\bdistrict\x18\x02 \x01(\tR\bdistrict\x12#\n" +
	"\rcurrent_price\x18\x03 \x01(\x02R\fcurrentPrice\x12\x1b\n" +
	"\tavg_30day\x18\x04 \x01(\x02R\bavg30day\x12\x1b\n" +
	"\tavg_90day\x18\x05 \x01(\x02R\bavg90day\x12\x1f\n" +
	"\vprice_trend\x18\x06 \x01(\tR\n" +
	"priceTrend\x12\x1d\n" +
	"\n" +
	"best_month\x18\a \x01(\tR\tbestMonth\x12\x1a\n" +
	"\badvisory\x18\b \x01(\tR\badvisory\"\xc2\x01\n" +
	"\x0fPestRiskRequest\x12\x1a\n" +
	"\bdistrict\x18\x01 \x01(\tR\bdistrict\x12\x16\n" +
	"\x06season\x18\x02 \x01(\tR\x06season\x12!\n" +
	"\fgrowth_stage\x18\x03 \x01(\tR\vgrowthStage\x12 \n" +
	"\vtemperature\x18\x04 \x01(\x02R\vtemperature\x12\x1a\n" +
	"\bhumidity\x18\x05 \x01(\x02R\bhumidity\x12\x1a\n" +
	"\brainfall\x18\x06 \x01(\x02R\brainfall\"\x90\x01\n" +
	"\bPestInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"risk_level\x18\x02 \x01(\tR\triskLevel\x12\x14\n" +
	"\x05signs\x18\x03 \x01(\tR\x05signs\x12\x16\n" +
	"\x06action\x18\x04 \x01(\tR\x06action\x12#\n" +
	"\retl_threshold\x18\x05 \x01(\tR\fetlThreshold\"\xc6\x01\n" +
	"\x10PestRiskResponse\x120\n" +
	"\bmetadata\x18\x01 \x01(\v2\x14.paddy.AgentMetadataR\bmetadata\x12\x1a\n" +
	"\bdistrict\x18\x02 \x01(\tR\bdistrict\x12!\n" +
	"\foverall_risk\x18\x03 \x01(\tR\voverallRisk\x12%\n" +
	"\x05pests\x18\x04 \x03(\v2\x0f.paddy.PestInfoR\x05pests\x12\x1a\n" +
	"\badvisory\x18\x05 \x01(\tR\badvisory2\xdd\x01\n" +
	"\x13OrchestratorService\x12A\n" +
	"\rRegisterAgent\x12\x18.paddy.AgentRegistration\x1a\x16.paddy.RegistrationAck\x12D\n" +
	"\x0fGetSystemStatus\x12\x14.paddy.StatusRequest\x1a\x1b.paddy.SystemStatusResponse\x12=\n" +
	"\n" +
	"RouteQuery\x12\x12.paddy.FarmerQuery\x1a\x1b.paddy.OrchestratorResponse2\xf4\x01\n" +
	"\x13WeatherAgentService\x12C\n" +
	"\x12GetWeatherForecast\x12\x15.paddy.WeatherRequest\x1a\x16.paddy.WeatherResponse\x12E\n" +
	"\x0fGetWeatherAlert\x12\x15.paddy.WeatherRequest\x1a\x1b.paddy.WeatherAlertResponse\x12Q\n" +
	"\x14GetHistoricalWeather\x12\x1b.paddy.HistoricalWeatherReq\x1a\x1c.paddy.HistoricalWeatherResp2L\n" +
	"\x10SoilAgentService\x128\n" +
	"\rGetSoilHealth\x12\x12.paddy.SoilRequest\x1a\x13.paddy.SoilResponse2d\n" +
	"\x16CropHealthAgentService\x12J\n" +
	"\x13GetCropHealthStatus\x12\x18.paddy.CropHealthRequest\x1a\x19.paddy.CropHealthResponse2V\n" +
	"\x12MarketAgentService\x12@\n" +
	"\x11GetMarketAdvisory\x12\x14.paddy.MarketRequest\x1a\x15.paddy.MarketResponse2V\n" +
	"\x14PestRiskAgentService\x12>\n" +
	"\vGetPestRisk\x12\x16.paddy.PestRiskRequest\x1a\x17.paddy.PestRiskResponseB#Z!github.com/AdiXgit/Capstone/protob\x06proto3"

var (
	file_proto_paddy_agents_proto_rawDescOnce sync.Once
	file_proto_paddy_agents_proto_rawDescData []byte
)

func file_proto_paddy_agents_proto_rawDescGZIP() []byte {
	file_proto_paddy_agents_proto_rawDescOnce.Do(func() {
		file_proto_paddy_agents_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_paddy_agents_proto_rawDesc), len(file_proto_paddy_agents_proto_rawDesc)))
	})
	return file_proto_paddy_agents_proto_rawDescData
}

var file_proto_paddy_agents_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_proto_paddy_agents_proto_goTypes = []any{
	(*AgentRegistration)(nil),     // 0: paddy.AgentRegistration
	(*RegistrationAck)(nil),       // 1: paddy.RegistrationAck
	(*StatusRequest)(nil),         // 2: paddy.StatusRequest
	(*SystemStatusResponse)(nil),  // 3: paddy.SystemStatusResponse
	(*FarmerQuery)(nil),           // 4: paddy.FarmerQuery
	(*AgentResult)(nil),           // 5: paddy.AgentResult
	(*OrchestratorResponse)(nil),  // 6: paddy.OrchestratorResponse
	(*AgentMetadata)(nil),         // 7: paddy.AgentMetadata
	(*WeatherRequest)(nil),        // 8: paddy.WeatherRequest
	(*DailyForecast)(nil),         // 9: paddy.DailyForecast
	(*WeatherResponse)(nil),       // 10: paddy.WeatherResponse
	(*WeatherAlertResponse)(nil),  // 11: paddy.WeatherAlertResponse
	(*HistoricalWeatherReq)(nil),  // 12: paddy.HistoricalWeatherReq
	(*HistoricalWeatherResp)(nil), // 13: paddy.HistoricalWeatherResp
	(*SoilRequest)(nil),           // 14: paddy.SoilRequest
	(*SoilResponse)(nil),          // 15: paddy.SoilResponse
	(*CropHealthRequest)(nil),     // 16: paddy.CropHealthRequest
	(*CropHealthResponse)(nil),    // 17: paddy.CropHealthResponse
	(*MarketRequest)(nil),         // 18: paddy.MarketRequest
	(*MarketResponse)(nil),        // 19: paddy.MarketResponse
	(*PestRiskRequest)(nil),       // 20: paddy.PestRiskRequest
	(*PestInfo)(nil),              // 21: paddy.PestInfo
	(*PestRiskResponse)(nil),      // 22: paddy.PestRiskResponse
}
var file_proto_paddy_agents_proto_depIdxs = []int32{
	5,  // 0: paddy.OrchestratorResponse.agent_results:type_name -> paddy.AgentResult
	7,  // 1: paddy.WeatherResponse.metadata:type_name -> paddy.AgentMetadata
	9,  // 2: paddy.WeatherResponse.forecast:type_name -> paddy.DailyForecast
	7,  // 3: paddy.WeatherAlertResponse.metadata:type_name -> paddy.AgentMetadata
	7,  // 4: paddy.HistoricalWeatherResp.metadata:type_name -> paddy.AgentMetadata
	10, // 5: paddy.HistoricalWeatherResp.records:type_name -> paddy.WeatherResponse
	7,  // 6: paddy.SoilResponse.metadata:type_name -> paddy.AgentMetadata
	7,  // 7: paddy.CropHealthResponse.metadata:type_name -> paddy.AgentMetadata
	7,  // 8: paddy.MarketResponse.metadata:type_name -> paddy.AgentMetadata
	7,  // 9: paddy.PestRiskResponse.metadata:type_name -> paddy.AgentMetadata
	21, // 10: paddy.PestRiskResponse.pests:type_name -> paddy.PestInfo
	0,  // 11: paddy.OrchestratorService.RegisterAgent:input_type -> paddy.AgentRegistration
	2,  // 12: paddy.OrchestratorService.GetSystemStatus:input_type -> paddy.StatusRequest
	4,  // 13: paddy.OrchestratorService.RouteQuery:input_type -> paddy.FarmerQuery
	8,  // 14: paddy.WeatherAgentService.GetWeatherForecast:input_type -> paddy.WeatherRequest
	8,  // 15: paddy.WeatherAgentService.GetWeatherAlert:input_type -> paddy.WeatherRequest
	12, // 16: paddy.WeatherAgentService.GetHistoricalWeather:input_type -> paddy.HistoricalWeatherReq
	14, // 17: paddy.SoilAgentService.GetSoilHealth:input_type -> paddy.SoilRequest
	16, // 18: paddy.CropHealthAgentService.GetCropHealthStatus:input_type -> paddy.CropHealthRequest
	18, // 19: paddy.MarketAgentService.GetMarketAdvisory:input_type -> paddy.MarketRequest
	20, // 20: paddy.PestRiskAgentService.GetPestRisk:input_type -> paddy.PestRiskRequest
	1,  // 21: paddy.OrchestratorService.RegisterAgent:output_type -> paddy.RegistrationAck
	3,  // 22: paddy.OrchestratorService.GetSystemStatus:output_type -> paddy.SystemStatusResponse
	6,  // 23: paddy.OrchestratorService.RouteQuery:output_type -> paddy.OrchestratorResponse
	10, // 24: paddy.WeatherAgentService.GetWeatherForecast:output_type -> paddy.WeatherResponse
	11, // 25: paddy.WeatherAgentService.GetWeatherAlert:output_type -> paddy.WeatherAlertResponse
	13, // 26: paddy.WeatherAgentService.GetHistoricalWeather:output_type -> paddy.HistoricalWeatherResp
	15, // 27: paddy.SoilAgentService.GetSoilHealth:output_type -> paddy.SoilResponse
	17, // 28: paddy.CropHealthAgentService.GetCropHealthStatus:output_type -> paddy.CropHealthResponse
	19, // 29: paddy.MarketAgentService.GetMarketAdvisory:output_type -> paddy.MarketResponse
	22, // 30: paddy.PestRiskAgentService.GetPestRisk:output_type -> paddy.PestRiskResponse
	21, // [21:31] is the sub-list for method output_type
	11, // [11:21] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_proto_paddy_agents_proto_init() }
func file_proto_paddy_agents_proto_init() {
	if File_proto_paddy_agents_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_paddy_agents_proto_rawDesc), len(file_proto_paddy_agents_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   6,
		},
		GoTypes:           file_proto_paddy_agents_proto_goTypes,
		DependencyIndexes: file_proto_paddy_agents_proto_depIdxs,
		MessageInfos:      file_proto_paddy_agents_proto_msgTypes,
	}.Build()
	File_proto_paddy_agents_proto = out.File
	file_proto_paddy_agents_proto_goTypes = nil
	file_proto_paddy_agents_proto_depIdxs = nil
}
