// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: proto/paddy_agents.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	OrchestratorService_RegisterAgent_FullMethodName   = "/paddy.OrchestratorService/RegisterAgent"
	OrchestratorService_GetSystemStatus_FullMethodName = "/paddy.OrchestratorService/GetSystemStatus"
	OrchestratorService_RouteQuery_FullMethodName      = "/paddy.OrchestratorService/RouteQuery"
)

// OrchestratorServiceClient is the client API for OrchestratorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ══════════════════════════════════════════════════════
// ORCHESTRATOR SERVICE
// ══════════════════════════════════════════════════════
type OrchestratorServiceClient interface {
	RegisterAgent(ctx context.Context, in *AgentRegistration, opts ...grpc.CallOption) (*RegistrationAck, error)
	GetSystemStatus(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*SystemStatusResponse, error)
	RouteQuery(ctx context.Context, in *FarmerQuery, opts ...grpc.CallOption) (*OrchestratorResponse, error)
}

type orchestratorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOrchestratorServiceClient(cc grpc.ClientConnInterface) OrchestratorServiceClient {
	return &orchestratorServiceClient{cc}
}

func (c *orchestratorServiceClient) RegisterAgent(ctx context.Context, in *AgentRegistration, opts ...grpc.CallOption) (*RegistrationAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegistrationAck)
	err := c.cc.Invoke(ctx, OrchestratorService_RegisterAgent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestratorServiceClient) GetSystemStatus(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*SystemStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SystemStatusResponse)
	err := c.cc.Invoke(ctx, OrchestratorService_GetSystemStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestratorServiceClient) RouteQuery(ctx context.Context, in *FarmerQuery, opts ...grpc.CallOption) (*OrchestratorResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OrchestratorResponse)
	err := c.cc.Invoke(ctx, OrchestratorService_RouteQuery_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrchestratorServiceServer is the server API for OrchestratorService service.
// All implementations must embed UnimplementedOrchestratorServiceServer
// for forward compatibility.
//
// ══════════════════════════════════════════════════════
// ORCHESTRATOR SERVICE
// ══════════════════════════════════════════════════════
type OrchestratorServiceServer interface {
	RegisterAgent(context.Context, *AgentRegistration) (*RegistrationAck, error)
	GetSystemStatus(context.Context, *StatusRequest) (*SystemStatusResponse, error)
	RouteQuery(context.Context, *FarmerQuery) (*OrchestratorResponse, error)
	mustEmbedUnimplementedOrchestratorServiceServer()
}

// UnimplementedOrchestratorServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOrchestratorServiceServer struct{}

func (UnimplementedOrchestratorServiceServer) RegisterAgent(context.Context, *AgentRegistration) (*RegistrationAck, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterAgent not implemented")
}
func (UnimplementedOrchestratorServiceServer) GetSystemStatus(context.Context, *StatusRequest) (*SystemStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSystemStatus not implemented")
}
func (UnimplementedOrchestratorServiceServer) RouteQuery(context.Context, *FarmerQuery) (*OrchestratorResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RouteQuery not implemented")
}
func (UnimplementedOrchestratorServiceServer) mustEmbedUnimplementedOrchestratorServiceServer() {}
func (UnimplementedOrchestratorServiceServer) testEmbeddedByValue()                             {}

// UnsafeOrchestratorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OrchestratorServiceServer will
// result in compilation errors.
type UnsafeOrchestratorServiceServer interface {
	mustEmbedUnimplementedOrchestratorServiceServer()
}

func RegisterOrchestratorServiceServer(s grpc.ServiceRegistrar, srv OrchestratorServiceServer) {
	// If the following call panics, it indicates UnimplementedOrchestratorServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OrchestratorService_ServiceDesc, srv)
}

func _OrchestratorService_RegisterAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AgentRegistration)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorServiceServer).RegisterAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrchestratorService_RegisterAgent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorServiceServer).RegisterAgent(ctx, req.(*AgentRegistration))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrchestratorService_GetSystemStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorServiceServer).GetSystemStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrchestratorService_GetSystemStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorServiceServer).GetSystemStatus(ctx, req.(*StatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrchestratorService_RouteQuery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FarmerQuery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorServiceServer).RouteQuery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrchestratorService_RouteQuery_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorServiceServer).RouteQuery(ctx, req.(*FarmerQuery))
	}
	return interceptor(ctx, in, info, handler)
}

// OrchestratorService_ServiceDesc is the grpc.ServiceDesc for OrchestratorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OrchestratorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "paddy.OrchestratorService",
	HandlerType: (*OrchestratorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterAgent",
			Handler:    _OrchestratorService_RegisterAgent_Handler,
		},
		{
			MethodName: "GetSystemStatus",
			Handler:    _OrchestratorService_GetSystemStatus_Handler,
		},
		{
			MethodName: "RouteQuery",
			Handler:    _OrchestratorService_RouteQuery_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/paddy_agents.proto",
}

const (
	WeatherAgentService_GetWeatherForecast_FullMethodName   = "/paddy.WeatherAgentService/GetWeatherForecast"
	WeatherAgentService_GetWeatherAlert_FullMethodName      = "/paddy.WeatherAgentService/GetWeatherAlert"
	WeatherAgentService_GetHistoricalWeather_FullMethodName = "/paddy.WeatherAgentService/GetHistoricalWeather"
)

// WeatherAgentServiceClient is the client API for WeatherAgentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ══════════════════════════════════════════════════════
// WEATHER AGENT SERVICE  (Aditya — matches weather.go exactly)
// ══════════════════════════════════════════════════════
type WeatherAgentServiceClient interface {
	GetWeatherForecast(ctx context.Context, in *WeatherRequest, opts ...grpc.CallOption) (*WeatherResponse, error)
	GetWeatherAlert(ctx context.Context, in *WeatherRequest, opts ...grpc.CallOption) (*WeatherAlertResponse, error)
	GetHistoricalWeather(ctx context.Context, in *HistoricalWeatherReq, opts ...grpc.CallOption) (*HistoricalWeatherResp, error)
}

type weatherAgentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWeatherAgentServiceClient(cc grpc.ClientConnInterface) WeatherAgentServiceClient {
	return &weatherAgentServiceClient{cc}
}

func (c *weatherAgentServiceClient) GetWeatherForecast(ctx context.Context, in *WeatherRequest, opts ...grpc.CallOption) (*WeatherResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WeatherResponse)
	err := c.cc.Invoke(ctx, WeatherAgentService_GetWeatherForecast_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *weatherAgentServiceClient) GetWeatherAlert(ctx context.Context, in *WeatherRequest, opts ...grpc.CallOption) (*WeatherAlertResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WeatherAlertResponse)
	err := c.cc.Invoke(ctx, WeatherAgentService_GetWeatherAlert_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *weatherAgentServiceClient) GetHistoricalWeather(ctx context.Context, in *HistoricalWeatherReq, opts ...grpc.CallOption) (*HistoricalWeatherResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HistoricalWeatherResp)
	err := c.cc.Invoke(ctx, WeatherAgentService_GetHistoricalWeather_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WeatherAgentServiceServer is the server API for WeatherAgentService service.
// All implementations must embed UnimplementedWeatherAgentServiceServer
// for forward compatibility.
//
// ══════════════════════════════════════════════════════
// WEATHER AGENT SERVICE  (Aditya — matches weather.go exactly)
// ══════════════════════════════════════════════════════
type WeatherAgentServiceServer interface {
	GetWeatherForecast(context.Context, *WeatherRequest) (*WeatherResponse, error)
	GetWeatherAlert(context.Context, *WeatherRequest) (*WeatherAlertResponse, error)
	GetHistoricalWeather(context.Context, *HistoricalWeatherReq) (*HistoricalWeatherResp, error)
	mustEmbedUnimplementedWeatherAgentServiceServer()
}

// UnimplementedWeatherAgentServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWeatherAgentServiceServer struct{}

func (UnimplementedWeatherAgentServiceServer) GetWeatherForecast(context.Context, *WeatherRequest) (*WeatherResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetWeatherForecast not implemented")
}
func (UnimplementedWeatherAgentServiceServer) GetWeatherAlert(context.Context, *WeatherRequest) (*WeatherAlertResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetWeatherAlert not implemented")
}
func (UnimplementedWeatherAgentServiceServer) GetHistoricalWeather(context.Context, *HistoricalWeatherReq) (*HistoricalWeatherResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetHistoricalWeather not implemented")
}
func (UnimplementedWeatherAgentServiceServer) mustEmbedUnimplementedWeatherAgentServiceServer() {}
func (UnimplementedWeatherAgentServiceServer) testEmbeddedByValue()                             {}

// UnsafeWeatherAgentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WeatherAgentServiceServer will
// result in compilation errors.
type UnsafeWeatherAgentServiceServer interface {
	mustEmbedUnimplementedWeatherAgentServiceServer()
}

func RegisterWeatherAgentServiceServer(s grpc.ServiceRegistrar, srv WeatherAgentServiceServer) {
	// If the following call panics, it indicates UnimplementedWeatherAgentServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WeatherAgentService_ServiceDesc, srv)
}

func _WeatherAgentService_GetWeatherForecast_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WeatherRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WeatherAgentServiceServer).GetWeatherForecast(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WeatherAgentService_GetWeatherForecast_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WeatherAgentServiceServer).GetWeatherForecast(ctx, req.(*WeatherRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WeatherAgentService_GetWeatherAlert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WeatherRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WeatherAgentServiceServer).GetWeatherAlert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WeatherAgentService_GetWeatherAlert_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WeatherAgentServiceServer).GetWeatherAlert(ctx, req.(*WeatherRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WeatherAgentService_GetHistoricalWeather_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HistoricalWeatherReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WeatherAgentServiceServer).GetHistoricalWeather(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WeatherAgentService_GetHistoricalWeather_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WeatherAgentServiceServer).GetHistoricalWeather(ctx, req.(*HistoricalWeatherReq))
	}
	return interceptor(ctx, in, info, handler)
}

// WeatherAgentService_ServiceDesc is the grpc.ServiceDesc for WeatherAgentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WeatherAgentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "paddy.WeatherAgentService",
	HandlerType: (*WeatherAgentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetWeatherForecast",
			Handler:    _WeatherAgentService_GetWeatherForecast_Handler,
		},
		{
			MethodName: "GetWeatherAlert",
			Handler:    _WeatherAgentService_GetWeatherAlert_Handler,
		},
		{
			MethodName: "GetHistoricalWeather",
			Handler:    _WeatherAgentService_GetHistoricalWeather_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/paddy_agents.proto",
}

const (
	SoilAgentService_GetSoilHealth_FullMethodName = "/paddy.SoilAgentService/GetSoilHealth"
)

// SoilAgentServiceClient is the client API for SoilAgentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ══════════════════════════════════════════════════════
// SOIL AGENT SERVICE  (Aman)
// Single RPC bundling NPK + Fertilizer + Yield + Trend
// so the orchestrator's existing GetSoilHealth call works unmodified
// ══════════════════════════════════════════════════════
type SoilAgentServiceClient interface {
	GetSoilHealth(ctx context.Context, in *SoilRequest, opts ...grpc.CallOption) (*SoilResponse, error)
}

type soilAgentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSoilAgentServiceClient(cc grpc.ClientConnInterface) SoilAgentServiceClient {
	return &soilAgentServiceClient{cc}
}

func (c *soilAgentServiceClient) GetSoilHealth(ctx context.Context, in *SoilRequest, opts ...grpc.CallOption) (*SoilResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SoilResponse)
	err := c.cc.Invoke(ctx, SoilAgentService_GetSoilHealth_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SoilAgentServiceServer is the server API for SoilAgentService service.
// All implementations must embed UnimplementedSoilAgentServiceServer
// for forward compatibility.
//
// ══════════════════════════════════════════════════════
// SOIL AGENT SERVICE  (Aman)
// Single RPC bundling NPK + Fertilizer + Yield + Trend
// so the orchestrator's existing GetSoilHealth call works unmodified
// ══════════════════════════════════════════════════════
type SoilAgentServiceServer interface {
	GetSoilHealth(context.Context, *SoilRequest) (*SoilResponse, error)
	mustEmbedUnimplementedSoilAgentServiceServer()
}

// UnimplementedSoilAgentServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSoilAgentServiceServer struct{}

func (UnimplementedSoilAgentServiceServer) GetSoilHealth(context.Context, *SoilRequest) (*SoilResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSoilHealth not implemented")
}
func (UnimplementedSoilAgentServiceServer) mustEmbedUnimplementedSoilAgentServiceServer() {}
func (UnimplementedSoilAgentServiceServer) testEmbeddedByValue()                          {}

// UnsafeSoilAgentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SoilAgentServiceServer will
// result in compilation errors.
type UnsafeSoilAgentServiceServer interface {
	mustEmbedUnimplementedSoilAgentServiceServer()
}

func RegisterSoilAgentServiceServer(s grpc.ServiceRegistrar, srv SoilAgentServiceServer) {
	// If the following call panics, it indicates UnimplementedSoilAgentServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SoilAgentService_ServiceDesc, srv)
}

func _SoilAgentService_GetSoilHealth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SoilRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SoilAgentServiceServer).GetSoilHealth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SoilAgentService_GetSoilHealth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SoilAgentServiceServer).GetSoilHealth(ctx, req.(*SoilRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SoilAgentService_ServiceDesc is the grpc.ServiceDesc for SoilAgentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SoilAgentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "paddy.SoilAgentService",
	HandlerType: (*SoilAgentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSoilHealth",
			Handler:    _SoilAgentService_GetSoilHealth_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/paddy_agents.proto",
}

const (
	CropHealthAgentService_GetCropHealthStatus_FullMethodName = "/paddy.CropHealthAgentService/GetCropHealthStatus"
)

// CropHealthAgentServiceClient is the client API for CropHealthAgentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ══════════════════════════════════════════════════════
// CROP HEALTH AGENT SERVICE  (Rishi)
// ══════════════════════════════════════════════════════
type CropHealthAgentServiceClient interface {
	GetCropHealthStatus(ctx context.Context, in *CropHealthRequest, opts ...grpc.CallOption) (*CropHealthResponse, error)
}

type cropHealthAgentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCropHealthAgentServiceClient(cc grpc.ClientConnInterface) CropHealthAgentServiceClient {
	return &cropHealthAgentServiceClient{cc}
}

func (c *cropHealthAgentServiceClient) GetCropHealthStatus(ctx context.Context, in *CropHealthRequest, opts ...grpc.CallOption) (*CropHealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CropHealthResponse)
	err := c.cc.Invoke(ctx, CropHealthAgentService_GetCropHealthStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CropHealthAgentServiceServer is the server API for CropHealthAgentService service.
// All implementations must embed UnimplementedCropHealthAgentServiceServer
// for forward compatibility.
//
// ══════════════════════════════════════════════════════
// CROP HEALTH AGENT SERVICE  (Rishi)
// ══════════════════════════════════════════════════════
type CropHealthAgentServiceServer interface {
	GetCropHealthStatus(context.Context, *CropHealthRequest) (*CropHealthResponse, error)
	mustEmbedUnimplementedCropHealthAgentServiceServer()
}

// UnimplementedCropHealthAgentServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCropHealthAgentServiceServer struct{}

func (UnimplementedCropHealthAgentServiceServer) GetCropHealthStatus(context.Context, *CropHealthRequest) (*CropHealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCropHealthStatus not implemented")
}
func (UnimplementedCropHealthAgentServiceServer) mustEmbedUnimplementedCropHealthAgentServiceServer() {
}
func (UnimplementedCropHealthAgentServiceServer) testEmbeddedByValue() {}

// UnsafeCropHealthAgentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CropHealthAgentServiceServer will
// result in compilation errors.
type UnsafeCropHealthAgentServiceServer interface {
	mustEmbedUnimplementedCropHealthAgentServiceServer()
}

func RegisterCropHealthAgentServiceServer(s grpc.ServiceRegistrar, srv CropHealthAgentServiceServer) {
	// If the following call panics, it indicates UnimplementedCropHealthAgentServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CropHealthAgentService_ServiceDesc, srv)
}

func _CropHealthAgentService_GetCropHealthStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CropHealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CropHealthAgentServiceServer).GetCropHealthStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CropHealthAgentService_GetCropHealthStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CropHealthAgentServiceServer).GetCropHealthStatus(ctx, req.(*CropHealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CropHealthAgentService_ServiceDesc is the grpc.ServiceDesc for CropHealthAgentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CropHealthAgentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "paddy.CropHealthAgentService",
	HandlerType: (*CropHealthAgentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCropHealthStatus",
			Handler:    _CropHealthAgentService_GetCropHealthStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/paddy_agents.proto",
}

const (
	MarketAgentService_GetMarketAdvisory_FullMethodName = "/paddy.MarketAgentService/GetMarketAdvisory"
)

// MarketAgentServiceClient is the client API for MarketAgentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ══════════════════════════════════════════════════════
// MARKET AGENT SERVICE  (Aman — NEW)
// ══════════════════════════════════════════════════════
type MarketAgentServiceClient interface {
	GetMarketAdvisory(ctx context.Context, in *MarketRequest, opts ...grpc.CallOption) (*MarketResponse, error)
}

type marketAgentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMarketAgentServiceClient(cc grpc.ClientConnInterface) MarketAgentServiceClient {
	return &marketAgentServiceClient{cc}
}

func (c *marketAgentServiceClient) GetMarketAdvisory(ctx context.Context, in *MarketRequest, opts ...grpc.CallOption) (*MarketResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MarketResponse)
	err := c.cc.Invoke(ctx, MarketAgentService_GetMarketAdvisory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MarketAgentServiceServer is the server API for MarketAgentService service.
// All implementations must embed UnimplementedMarketAgentServiceServer
// for forward compatibility.
//
// ══════════════════════════════════════════════════════
// MARKET AGENT SERVICE  (Aman — NEW)
// ══════════════════════════════════════════════════════
type MarketAgentServiceServer interface {
	GetMarketAdvisory(context.Context, *MarketRequest) (*MarketResponse, error)
	mustEmbedUnimplementedMarketAgentServiceServer()
}

// UnimplementedMarketAgentServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMarketAgentServiceServer struct{}

func (UnimplementedMarketAgentServiceServer) GetMarketAdvisory(context.Context, *MarketRequest) (*MarketResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMarketAdvisory not implemented")
}
func (UnimplementedMarketAgentServiceServer) mustEmbedUnimplementedMarketAgentServiceServer() {}
func (UnimplementedMarketAgentServiceServer) testEmbeddedByValue()                            {}

// UnsafeMarketAgentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MarketAgentServiceServer will
// result in compilation errors.
type UnsafeMarketAgentServiceServer interface {
	mustEmbedUnimplementedMarketAgentServiceServer()
}

func RegisterMarketAgentServiceServer(s grpc.ServiceRegistrar, srv MarketAgentServiceServer) {
	// If the following call panics, it indicates UnimplementedMarketAgentServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MarketAgentService_ServiceDesc, srv)
}

func _MarketAgentService_GetMarketAdvisory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MarketRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketAgentServiceServer).GetMarketAdvisory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MarketAgentService_GetMarketAdvisory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketAgentServiceServer).GetMarketAdvisory(ctx, req.(*MarketRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MarketAgentService_ServiceDesc is the grpc.ServiceDesc for MarketAgentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MarketAgentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "paddy.MarketAgentService",
	HandlerType: (*MarketAgentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMarketAdvisory",
			Handler:    _MarketAgentService_GetMarketAdvisory_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/paddy_agents.proto",
}

const (
	PestRiskAgentService_GetPestRisk_FullMethodName = "/paddy.PestRiskAgentService/GetPestRisk"
)

// PestRiskAgentServiceClient is the client API for PestRiskAgentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ══════════════════════════════════════════════════════
// PEST RISK AGENT SERVICE  (Aditya — NEW)
// ══════════════════════════════════════════════════════
type PestRiskAgentServiceClient interface {
	GetPestRisk(ctx context.Context, in *PestRiskRequest, opts ...grpc.CallOption) (*PestRiskResponse, error)
}

type pestRiskAgentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPestRiskAgentServiceClient(cc grpc.ClientConnInterface) PestRiskAgentServiceClient {
	return &pestRiskAgentServiceClient{cc}
}

func (c *pestRiskAgentServiceClient) GetPestRisk(ctx context.Context, in *PestRiskRequest, opts ...grpc.CallOption) (*PestRiskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PestRiskResponse)
	err := c.cc.Invoke(ctx, PestRiskAgentService_GetPestRisk_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PestRiskAgentServiceServer is the server API for PestRiskAgentService service.
// All implementations must embed UnimplementedPestRiskAgentServiceServer
// for forward compatibility.
//
// ══════════════════════════════════════════════════════
// PEST RISK AGENT SERVICE  (Aditya — NEW)
// ══════════════════════════════════════════════════════
type PestRiskAgentServiceServer interface {
	GetPestRisk(context.Context, *PestRiskRequest) (*PestRiskResponse, error)
	mustEmbedUnimplementedPestRiskAgentServiceServer()
}

// UnimplementedPestRiskAgentServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPestRiskAgentServiceServer struct{}

func (UnimplementedPestRiskAgentServiceServer) GetPestRisk(context.Context, *PestRiskRequest) (*PestRiskResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPestRisk not implemented")
}
func (UnimplementedPestRiskAgentServiceServer) mustEmbedUnimplementedPestRiskAgentServiceServer() {}
func (UnimplementedPestRiskAgentServiceServer) testEmbeddedByValue()                              {}

// UnsafePestRiskAgentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PestRiskAgentServiceServer will
// result in compilation errors.
type UnsafePestRiskAgentServiceServer interface {
	mustEmbedUnimplementedPestRiskAgentServiceServer()
}

func RegisterPestRiskAgentServiceServer(s grpc.ServiceRegistrar, srv PestRiskAgentServiceServer) {
	// If the following call panics, it indicates UnimplementedPestRiskAgentServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PestRiskAgentService_ServiceDesc, srv)
}

func _PestRiskAgentService_GetPestRisk_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PestRiskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PestRiskAgentServiceServer).GetPestRisk(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PestRiskAgentService_GetPestRisk_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PestRiskAgentServiceServer).GetPestRisk(ctx, req.(*PestRiskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PestRiskAgentService_ServiceDesc is the grpc.ServiceDesc for PestRiskAgentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PestRiskAgentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "paddy.PestRiskAgentService",
	HandlerType: (*PestRiskAgentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPestRisk",
			Handler:    _PestRiskAgentService_GetPestRisk_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/paddy_agents.proto",
}
